[package]
name = "backend"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-cors = "0.6.4"
actix-jwt-auth-middleware = "0.3.0"
actix-web = "4.1"
actix-web-httpauth = "0.8.0"
alcoholic_jwt = "4091.0.0"
aws-config = "0.56.0"
aws-sdk-cognitoidentityprovider = "0.29.0"
aws-sdk-s3 = "0.29.0"
chrono = "0.4.26"
convert_case = "0.6.0"
csv = "1.2.2"
derive_more = "0.99.17"
diesel = { version = "2.1.0", features = ["postgres", "r2d2", "chrono", "serde_json"] }
diesel-enum = "0.1.0"
diesel_migrations = "2.1.0"
dotenv = "0.15.0"
env_logger = "0.10.0"
log = "0.4.19"
mio = { version = "0.7.14", features = ["tcp", "os-poll"] }
mysql_async = "0.26.0"
reqwest = {version = "0.11.18", features = ["json"] }
serde = { version = "1.0.174", features = ["derive"] }
serde_derive = "1.0.174"
serde_json = "1.0.103"
statrs = "0.16.0"
tokio = { version = "1", features = ["full"] }
tupleops = "0.1.1"

[dependencies.uuid]
version = "1.4.1"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[env]
AUTHORITY = "https://cognito-idp.us-west-2.amazonaws.com/us-west-2_fL1j2xXwT/"
