apiVersion: v1
kind: Service
metadata:
  name: pago-mysql-service
  namespace: pago
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: pago-mysql
  type: ClusterIP
