apiVersion: v1
kind: Service
metadata:
  name: pago-frontend-service
  namespace: pago
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"3000":"http-service-backendconfig"}}'
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: pago-frontend
  type: NodePort
